// dummyData.js
const transactions = [
  {
    id: '001',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    name: 'John Doe',
    email: 'john.doe@email.com',
  },
  {
    id: '002',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    name: 'Jane Smith',
    email: 'jane.smith@email.com',
  },
  {
    id: '003',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    name: 'Michael Johnson',
    email: 'michael.johnson@email.com',
  },
  {
    id: '004',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    name: 'Emily Brown',
    email: 'emily.brown@email.com',
  },
  {
    id: '005',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    name: 'David Wilson',
    email: 'david.wilson@email.com',
  },
  {
    id: '006',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    name: 'Sarah Miller',
    email: 'sarah.miller@email.com',
  },
  {
    id: '007',
    avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    name: 'Kevin Lee',
    email: 'kevin.lee@email.com',
  },
  {
    id: '008',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    name: 'John Doe',
    email: 'john.doe@email.com',
  },
  {
    id: '009',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    name: 'Jane Smith',
    email: 'jane.smith@email.com',
  },
  {
    id: '010',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    name: 'Michael Johnson',
    email: 'michael.johnson@email.com',
  },
  {
    id: '011',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    name: 'Emily Brown',
    email: 'emily.brown@email.com',
  },
  {
    id: '012',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    name: 'David Wilson',
    email: 'david.wilson@email.com',
  },
  {
    id: '013',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    name: 'Sarah Miller',
    email: 'sarah.miller@email.com',
  },
  {
    id: '014',
    avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    name: 'Kevin Lee',
    email: 'kevin.lee@email.com',
  },
  {
    id: '015',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    name: 'John Doe',
    email: 'john.doe@email.com',
  },
  {
    id: '016',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    name: 'Jane Smith',
    email: 'jane.smith@email.com',
  },
  {
    id: '017',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    name: 'Michael Johnson',
    email: 'michael.johnson@email.com',
  },
  {
    id: '018',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    name: 'Emily Brown',
    email: 'emily.brown@email.com',
  },
  {
    id: '019',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    name: 'David Wilson',
    email: 'david.wilson@email.com',
  },
  {
    id: '020',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    name: 'Sarah Miller',
    email: 'sarah.miller@email.com',
  },
  {
    id: '021',
    avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    name: 'Kevin Lee',
    email: 'kevin.lee@email.com',
  },
  {
    id: '022',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    name: 'John Doe',
    email: 'john.doe@email.com',
  },
  {
    id: '023',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    name: 'Jane Smith',
    email: 'jane.smith@email.com',
  },
  {
    id: '024',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    name: 'Michael Johnson',
    email: 'michael.johnson@email.com',
  },
  {
    id: '025',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    name: 'Emily Brown',
    email: 'emily.brown@email.com',
  },
  {
    id: '026',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    name: 'David Wilson',
    email: 'david.wilson@email.com',
  },
  {
    id: '027',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    name: 'Sarah Miller',
    email: 'sarah.miller@email.com',
  },
  {
    id: '028',
    avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    name: 'Kevin Lee',
    email: 'kevin.lee@email.com',
  },
  {
    id: '029',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    name: 'John Doe',
    email: 'john.doe@email.com',
  },
  {
    id: '030',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    name: 'Jane Smith',
    email: 'jane.smith@email.com',
  },
  {
    id: '031',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    name: 'Michael Johnson',
    email: 'michael.johnson@email.com',
  },
  {
    id: '032',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    name: 'Emily Brown',
    email: 'emily.brown@email.com',
  },
  {
    id: '033',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    name: 'David Wilson',
    email: 'david.wilson@email.com',
  },
  {
    id: '034',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    name: 'Sarah Miller',
    email: 'sarah.miller@email.com',
  },
  {
    id: '035',
    avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    name: 'Kevin Lee',
    email: 'kevin.lee@email.com',
  },
];

export default transactions;
